import streamlit as st
import pandas as pd
import yfinance as yf
import numpy as np
import datetime as dt

# -------------------
# Indicator Functions
# -------------------

def ema(series, period):
    return series.ewm(span=period, adjust=False).mean()

def supertrend(df, period=10, multiplier=3):
    hl2 = (df['High'] + df['Low']) / 2
    atr = df['High'].rolling(period).max() - df['Low'].rolling(period).min()
    atr = atr.ewm(alpha=1/period, adjust=False).mean()

    upperband = hl2 + (multiplier * atr)
    lowerband = hl2 - (multiplier * atr)

    st_dir = [True] * len(df)  # True = bullish, False = bearish
    st_val = [0] * len(df)

    for i in range(1, len(df)):
        if df['Close'][i] > upperband[i-1]:
            st_dir[i] = True
        elif df['Close'][i] < lowerband[i-1]:
            st_dir[i] = False
        else:
            st_dir[i] = st_dir[i-1]
            if st_dir[i] and lowerband[i] < lowerband[i-1]:
                lowerband[i] = lowerband[i-1]
            if not st_dir[i] and upperband[i] > upperband[i-1]:
                upperband[i] = upperband[i-1]

        st_val[i] = lowerband[i] if st_dir[i] else upperband[i]

    df['Supertrend'] = st_val
    df['ST_Dir'] = st_dir
    return df

def pivot_points(df):
    last = df.iloc[-2]  # Use yesterday's OHLC for today's pivots
    P = (last['High'] + last['Low'] + last['Close']) / 3
    R1 = 2*P - last['Low']
    S1 = 2*P - last['High']
    R2 = P + (last['High'] - last['Low'])
    S2 = P - (last['High'] - last['Low'])
    return P, R1, S1, R2, S2

# -------------------
# Scanner Logic
# -------------------
def check_signal(df):
    if len(df) < 200:
        return None

    df['EMA200'] = ema(df['Close'], 200)
    df = supertrend(df)

    P, R1, S1, R2, S2 = pivot_points(df)
    last = df.iloc[-1]

    if last['Close'] > last['EMA200'] and last['ST_Dir'] and last['Close'] > P:
        return {"Signal": "BUY", "Target": R1, "SL": last['Supertrend']}
    elif last['Close'] < last['EMA200'] and not last['ST_Dir'] and last['Close'] < P:
        return {"Signal": "SELL", "Target": S1, "SL": last['Supertrend']}
    return None

# -------------------
# Streamlit App
# -------------------
st.set_page_config(page_title="Swing Scanner – Supertrend + Pivot + EMA200", layout="wide")
st.title("📊 NSE Swing Trading Scanner – Supertrend + Pivot + EMA200")

#nse_symbols = [
   # "RELIANCE.NS", "TCS.NS", "INFY.NS", "HDFCBANK.NS", "ICICIBANK.NS", 
   # "SBIN.NS", "HINDUNILVR.NS", "KOTAKBANK.NS", "ITC.NS", "LT.NS"
#]  # You can replace this with NIFTY 100 list
nse_symbols = [
        '360ONE.NS',
        '3MINDIA.NS',
        'ABB.NS',
        'ACC.NS',
        'ACMESOLAR.NS',
        'AIAENG.NS',
        'APLAPOLLO.NS',
        'AUBANK.NS',
        'AWL.NS',
        'AADHARHFC.NS',
        'AARTIIND.NS',
        'AAVAS.NS',
        'ABBOTINDIA.NS',
        'ACE.NS',
        'ADANIENSOL.NS',
        'ADANIENT.NS',
        'ADANIGREEN.NS',
        'ADANIPORTS.NS',
        'ADANIPOWER.NS',
        'ATGL.NS',
        'ABCAPITAL.NS',
        'ABFRL.NS',
        'ABREL.NS',
        'ABSLAMC.NS',
        'AEGISLOG.NS',
        'AFCONS.NS',
        'AFFLE.NS',
        'AJANTPHARM.NS',
        'AKUMS.NS',
        'APLLTD.NS',
        'ALIVUS.NS',
        'ALKEM.NS',
        'ALKYLAMINE.NS',
        'ALOKINDS.NS',
        'ARE&M.NS',
        'AMBER.NS',
        'AMBUJACEM.NS',
        'ANANDRATHI.NS',
        'ANANTRAJ.NS',
        'ANGELONE.NS',
        'APARINDS.NS',
        'APOLLOHOSP.NS',
        'APOLLOTYRE.NS',
        'APTUS.NS',
        'ASAHIINDIA.NS',
        'ASHOKLEY.NS',
        'ASIANPAINT.NS',
        'ASTERDM.NS',
        'ASTRAZEN.NS',
        'ASTRAL.NS',
        'ATUL.NS',
        'AUROPHARMA.NS',
        'AIIL.NS',
        'DMART.NS',
        'AXISBANK.NS',
        'BASF.NS',
        'BEML.NS',
        'BLS.NS',
        'BSE.NS',
        'BAJAJ-AUTO.NS',
        'BAJFINANCE.NS',
        'BAJAJFINSV.NS',
        'BAJAJHLDNG.NS',
        'BAJAJHFL.NS',
        'BALKRISIND.NS',
        'BALRAMCHIN.NS',
        'BANDHANBNK.NS',
        'BANKBARODA.NS',
        'BANKINDIA.NS',
        'MAHABANK.NS',
        'BATAINDIA.NS',
        'BAYERCROP.NS',
        'BERGEPAINT.NS',
        'BDL.NS',
        'BEL.NS',
        'BHARATFORG.NS',
        'BHEL.NS',
        'BPCL.NS',
        'BHARTIARTL.NS',
        'BHARTIHEXA.NS',
        'BIKAJI.NS',
        'BIOCON.NS',
        'BSOFT.NS',
        'BLUEDART.NS',
        'BLUESTARCO.NS',
        'BBTC.NS',
        'BOSCHLTD.NS',
        'FIRSTCRY.NS',
        'BRIGADE.NS',
        'BRITANNIA.NS',
        'MAPMYINDIA.NS',
        'CCL.NS',
        'CESC.NS',
        'CGPOWER.NS',
        'CRISIL.NS',
        'CAMPUS.NS',
        'CANFINHOME.NS',
        'CANBK.NS',
        'CAPLIPOINT.NS',
        'CGCL.NS',
        'CARBORUNIV.NS',
        'CASTROLIND.NS',
        'CEATLTD.NS',
        'CENTRALBK.NS',
        'CDSL.NS',
        'CENTURYPLY.NS',
        'CERA.NS',
        'CHALET.NS',
        'CHAMBLFERT.NS',
        'CHENNPETRO.NS',
        'CHOLAHLDNG.NS',
        'CHOLAFIN.NS',
        'CIPLA.NS',
        'CUB.NS',
        'CLEAN.NS',
        'COALINDIA.NS',
        'COCHINSHIP.NS',
        'COFORGE.NS',
        'COHANCE.NS',
        'COLPAL.NS',
        'CAMS.NS',
        'CONCORDBIO.NS',
        'CONCOR.NS',
        'COROMANDEL.NS',
        'CRAFTSMAN.NS',
        'CREDITACC.NS',
        'CROMPTON.NS',
        'CUMMINSIND.NS',
        'CYIENT.NS',
        'DCMSHRIRAM.NS',
        'DLF.NS',
        'DOMS.NS',
        'DABUR.NS',
        'DALBHARAT.NS',
        'DATAPATTNS.NS',
        'DEEPAKFERT.NS',
        'DEEPAKNTR.NS',
        'DELHIVERY.NS',
        'DEVYANI.NS',
        'DIVISLAB.NS',
        'DIXON.NS',
        'LALPATHLAB.NS',
        'DRREDDY.NS',   
        'EIDPARRY.NS',
        'EIHOTEL.NS',
        'EICHERMOT.NS',
        'ELECON.NS',
        'ELGIEQUIP.NS',
        'EMAMILTD.NS',
        'EMCURE.NS',
        'ENDURANCE.NS',
        'ENGINERSIN.NS',
        'ERIS.NS',
        'ESCORTS.NS',
        'ETERNAL.NS',
        'EXIDEIND.NS',
        'NYKAA.NS',
        'FEDERALBNK.NS',
        'FACT.NS',
        'FINCABLES.NS',
        'FINPIPE.NS',
        'FSL.NS',
        'FIVESTAR.NS',
        'FORTIS.NS',
        'GAIL.NS',
        'GVT&D.NS',
        'GMRAIRPORT.NS',
        'GRSE.NS',
        'GICRE.NS',
        'GILLETTE.NS',
        'GLAND.NS',
        'GLAXO.NS',
        'GLENMARK.NS',
        'MEDANTA.NS',
        'GODIGIT.NS',
        'GPIL.NS',
        'GODFRYPHLP.NS',
        'GODREJAGRO.NS',
        'GODREJCP.NS',
        'GODREJIND.NS',
        'GODREJPROP.NS',
        'GRANULES.NS',
        'GRAPHITE.NS',
        'GRASIM.NS',
        'GRAVITA.NS',
        'GESHIP.NS',
        'FLUOROCHEM.NS',
        'GUJGASLTD.NS',
        'GMDCLTD.NS',
        'GNFC.NS',
        'GPPL.NS',
        'GSPL.NS',
        'HEG.NS',
        'HBLENGINE.NS',
        'HCLTECH.NS',
        'HDFCAMC.NS',
        'HDFCBANK.NS',
        'HDFCLIFE.NS',
        'HFCL.NS',
        'HAPPSTMNDS.NS',
        'HAVELLS.NS',
        'HEROMOTOCO.NS',
        'HSCL.NS',
        'HINDALCO.NS',
        'HAL.NS',
        'HINDCOPPER.NS',
        'HINDPETRO.NS',
        'HINDUNILVR.NS',
        'HINDZINC.NS',
        'POWERINDIA.NS',
        'HOMEFIRST.NS',
        'HONASA.NS',
        'HONAUT.NS',
        'HUDCO.NS',
        'HYUNDAI.NS',
        'ICICIBANK.NS',
        'ICICIGI.NS',
        'ICICIPRULI.NS',
        'IDBI.NS',
        'IDFCFIRSTB.NS',
        'IFCI.NS',
        'IIFL.NS',
        'INOXINDIA.NS',
        'IRB.NS',
        'IRCON.NS',
        'ITC.NS',
        'ITI.NS',
        'INDGN.NS',
        'INDIACEM.NS',
        'INDIAMART.NS',
        'INDIANB.NS',
        'IEX.NS',
        'INDHOTEL.NS',
        'IOC.NS',
        'IOB.NS',
        'IRCTC.NS',
        'IRFC.NS',
        'IREDA.NS',
        'IGL.NS',
        'INDUSTOWER.NS',
        'INDUSINDBK.NS',
        'NAUKRI.NS',
        'INFY.NS',
        'INOXWIND.NS',
        'INTELLECT.NS',
        'INDIGO.NS',
        'IGIL.NS',
        'IKS.NS',
        'IPCALAB.NS',
        'JBCHEPHARM.NS',
        'JKCEMENT.NS',
        'JBMA.NS',
        'JKTYRE.NS',
        'JMFINANCIL.NS',
        'JSWENERGY.NS',
        'JSWHL.NS',
        'JSWINFRA.NS',
        'JSWSTEEL.NS',
        'JPPOWER.NS',
        'J&KBANK.NS',
        'JINDALSAW.NS',
        'JSL.NS',
        'JINDALSTEL.NS',
        'JIOFIN.NS',
        'JUBLFOOD.NS',
        'JUBLINGREA.NS',
        'JUBLPHARMA.NS',
        'JWL.NS',
        'JUSTDIAL.NS',
        'JYOTHYLAB.NS',
        'JYOTICNC.NS',
        'KPRMILL.NS',
        'KEI.NS',
        'KNRCON.NS',
        'KPITTECH.NS',
        'KAJARIACER.NS',
        'KPIL.NS',
        'KALYANKJIL.NS',
        'KANSAINER.NS',
        'KARURVYSYA.NS',
        'KAYNES.NS',
        'KEC.NS',
        'KFINTECH.NS',
        'KIRLOSBROS.NS',
        'KIRLOSENG.NS',
        'KOTAKBANK.NS',
        'KIMS.NS',
        'LTF.NS',
        'LTTS.NS',
        'LICHSGFIN.NS',
        'LTFOODS.NS',
        'LTIM.NS',
        'LT.NS',
        'LATENTVIEW.NS',
        'LAURUSLABS.NS',
        'LEMONTREE.NS',
        'LICI.NS',
        'LINDEINDIA.NS',
        'LLOYDSME.NS',
        'LUPIN.NS',
        'MMTC.NS',
        'MRF.NS',
        'LODHA.NS',
        'MGL.NS',
        'MAHSEAMLES.NS',
        'M&MFIN.NS',
        'M&M.NS',
        'MANAPPURAM.NS',
        'MRPL.NS',
        'MANKIND.NS',
        'MARICO.NS',
        'MARUTI.NS',
        'MASTEK.NS',
        'MFSL.NS',
        'MAXHEALTH.NS',
        'MAZDOCK.NS',
        'METROPOLIS.NS',
        'MINDACORP.NS',
        'MSUMI.NS',
        'MOTILALOFS.NS',
        'MPHASIS.NS',
        'MCX.NS',
        'MUTHOOTFIN.NS',
        'NATCOPHARM.NS',
        'NBCC.NS',
        'NCC.NS',
        'NHPC.NS',
        'NLCINDIA.NS',
        'NMDC.NS',
        'NSLNISP.NS',
        'NTPCGREEN.NS',
        'NTPC.NS',
        'NH.NS',
        'NATIONALUM.NS',
        'NAVA.NS',
        'NAVINFLUOR.NS',
        'NESTLEIND.NS',
        'NETWEB.NS',
        'NETWORK18.NS',
        'NEULANDLAB.NS',
        'NEWGEN.NS',
        'NAM-INDIA.NS',
        'NIVABUPA.NS',
        'NUVAMA.NS',
        'OBEROIRLTY.NS',
        'ONGC.NS',
        'OIL.NS',
        'OLAELEC.NS',
        'OLECTRA.NS',
        'PAYTM.NS',
        'OFSS.NS',
        'POLICYBZR.NS',
        'PCBL.NS',
        'PGEL.NS',
        'PIIND.NS',
        'PNBHOUSING.NS',
        'PNCINFRA.NS',
        'PTCIL.NS',
        'PVRINOX.NS',
        'PAGEIND.NS',
        'PATANJALI.NS',
        'PERSISTENT.NS',
        'PETRONET.NS',
        'PFIZER.NS',
        'PHOENIXLTD.NS',
        'PIDILITIND.NS',
        'PEL.NS',
        'PPLPHARMA.NS',
        'POLYMED.NS',
        'POLYCAB.NS',
        'POONAWALLA.NS',
        'PFC.NS',
        'POWERGRID.NS',
        'PRAJIND.NS',
        'PREMIERENE.NS',
        'PRESTIGE.NS',
        'PNB.NS',
        'RRKABEL.NS',
        'RBLBANK.NS',
        'RECLTD.NS',
        'RHIM.NS',
        'RITES.NS',
        'RADICO.NS',
        'RVNL.NS',
        'RAILTEL.NS',
        'RAINBOW.NS',
        'RKFORGE.NS',
        'RCF.NS',
        'RTNINDIA.NS',
        'RAYMONDLSL.NS',
        'RAYMOND.NS',
        'REDINGTON.NS',
        'RELIANCE.NS',
        'RPOWER.NS',
        'ROUTE.NS',
        'SBFC.NS',
        'SBICARD.NS',
        'SBILIFE.NS',
        'SJVN.NS',
        'SKFINDIA.NS',
        'SRF.NS',
        'SAGILITY.NS',
        'SAILIFE.NS',
        'SAMMAANCAP.NS',
        'MOTHERSON.NS',
        'SAPPHIRE.NS',
        'SARDAEN.NS',
        'SAREGAMA.NS',
        'SCHAEFFLER.NS',
        'SCHNEIDER.NS',
        'SCI.NS',
        'SHREECEM.NS',
        'RENUKA.NS',
        'SHRIRAMFIN.NS',
        'SHYAMMETL.NS',
        'SIEMENS.NS',
        'SIGNATURE.NS',
        'SOBHA.NS',
        'SOLARINDS.NS',
        'SONACOMS.NS',
        'SONATSOFTW.NS',
        'STARHEALTH.NS',
        'SBIN.NS',
        'SAIL.NS',
        'SWSOLAR.NS',
        'SUMICHEM.NS',
        'SUNPHARMA.NS',
        'SUNTV.NS',
        'SUNDARMFIN.NS',
        'SUNDRMFAST.NS',
        'SUPREMEIND.NS',
        'SUZLON.NS',
        'SWANENERGY.NS',
        'SWIGGY.NS',
        'SYNGENE.NS',
        'SYRMA.NS',
        'TBOTEK.NS',
        'TVSMOTOR.NS',
        'TANLA.NS',
        'TATACHEM.NS',
        'TATACOMM.NS',
        'TCS.NS',
        'TATACONSUM.NS',
        'TATAELXSI.NS',
        'TATAINVEST.NS',
        'TATAMOTORS.NS',
        'TATAPOWER.NS',
        'TATASTEEL.NS',
        'TATATECH.NS',
        'TTML.NS',
        'TECHM.NS',
        'TECHNOE.NS',
        'TEJASNET.NS',
        'NIACL.NS',
        'RAMCOCEM.NS',
        'THERMAX.NS',
        'TIMKEN.NS',
        'TITAGARH.NS',
        'TITAN.NS',
        'TORNTPHARM.NS',
        'TORNTPOWER.NS',
        'TARIL.NS',
        'TRENT.NS',
        'TRIDENT.NS',
        'TRIVENI.NS',
        'TRITURBINE.NS',
        'TIINDIA.NS',
        'UCOBANK.NS',
        'UNOMINDA.NS',
        'UPL.NS',
        'UTIAMC.NS',
        'ULTRACEMCO.NS',
        'UNIONBANK.NS',
        'UBL.NS',
        'UNITDSPR.NS',
        'USHAMART.NS',
        'VGUARD.NS',
        'DBREALTY.NS',
        'VTL.NS',
        'VBL.NS',
        'MANYAVAR.NS',
        'VEDL.NS',
        'VIJAYA.NS',
        'VMM.NS',
        'IDEA.NS',
        'VOLTAS.NS',
        'WAAREEENER.NS',
        'WELCORP.NS',
        'WELSPUNLIV.NS',
        'WESTLIFE.NS',
        'WHIRLPOOL.NS',
        'WIPRO.NS',
        'WOCKPHARMA.NS',
        'YESBANK.NS',
        'ZFCVINDIA.NS',
        'ZEEL.NS',
        'ZENTEC.NS',
        'ZENSARTECH.NS',
        'ZYDUSLIFE.NS',
        'ECLERX.NS',
    ]
    

start = dt.date.today() - dt.timedelta(days=300)
end = dt.date.today()

results = []
for symbol in nse_symbols:
    try:
        df = yf.download(symbol, start=start, end=end, interval="1d")
        df.dropna(inplace=True)
        sig = check_signal(df)
        if sig:
            results.append({
                "Stock": symbol.replace(".NS", ""),
                "Signal": sig["Signal"],
                "Close": round(df['Close'].iloc[-1], 2),
                "Target": round(sig["Target"], 2),
                "Stop Loss": round(sig["SL"], 2)
            })
    except Exception as e:
        st.error(f"{symbol} -> {e}")

if results:
    st.subheader("📈 Trade Opportunities Today")
    df_res = pd.DataFrame(results)
    st.dataframe(df_res)
else:
    st.info("No trade setups found today as per strategy.")
